image: node:16.13.1-alpine3.14

before_script:
  - npm install
  - npm cache --force

stages:
  - Security
  - Static Analysis
  - Test
  - Build

gitleaks:
  stage: Security
  before_script:
    - ''
  image:
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - pwd
    - cd $CI_PROJECT_DIR
    - pwd
    - gitleaks --verbose --source . --redact --report-format json --report-path gitlealks-report.json

audit:
  stage: Security
  before_script:
    - npm audit

eslint:
  stage: Static Analysis
  script:
    - npm prebuild

hadolint:
  stage: Static Analysis
  before_script:
    - ''
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile

postman:
  stage: Test
  image:
    name: postman/newman
    entrypoint: [""]
  script:
    - newman --version
    - npm install -g newman-reporter-html
    - newman run collection.json --reporter cli,html --reporter-html-export report.html

build:
  stage: Build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - export TAG="${CI_COMMIT_TAG:-latest" && echo $CI_COMMIT_TAG
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t $CI_REGISTERY_IMAGE:$TAG .
    - docker push $CI_REGISTERY_IMAGE:$TAG
  only:
    - main
