version: '3.8'

services:

  db:
    image: mariadb:10.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
